kind: pipeline
name: drone

workspace:
    base: /go
    path: src/github.com/Yajun312890225/DroneTest
  
steps:
    - name: build
      image: golang:latest
      commands:
        - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main main.go
    - name: publish 
        image: plugins/docker
        registry: https://registry.wisesoft.net.cn/
        repo: DroneTest 
        tags:
            - latest
    